[server]
headless = true
port = 8501
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

[theme]
primaryColor = "#0F766E"
backgroundColor = "#F4F5FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#12162A"
font = "sans serif"
